# Generated by Django 4.2.4 on 2023-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chain_type',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('no chain', 'No chain')], default='no chain', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray')], default='black', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=10),
        ),
    ]
