# Generated by Django 4.2.4 on 2023-08-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='email@provider.com', max_length=254, unique=True),
        ),
    ]
